#!/bin/bash

. lib.sh || exit

gpg_export_public() {
	gpg --export "$@"
}

gpg_export_secret() {
	gpg --export-secret-keys "$@"
}

eval "$(globaltraps)"

WORKDIR="$(mktemp -d)"
ltrap "rm -rf '$WORKDIR'"

KEY_ID="${@:$#}"
GPG_EXPORT_ARGS=( "${@:1:$#-1}" )

if [[ $KEY_ID == *! ]]; then
	log "Exporting subkey only: ${KEY_ID%!}"
	gpg_export_secret() {
		gpg --export-secret-subkeys "$@"
	}
fi

install -dm700 "$WORKDIR/gnupg"

log "When prompted, enter the old passphrase"
gpg_export_secret --export-options backup "${KEY_ID}" >"$WORKDIR/gpg_private"

export GNUPGHOME="$WORKDIR/gnupg"
gpg --import --import-options restore <"$WORKDIR/gpg_private"
log "When prompted, enter the old passphrase and then the new passphrase"
gpg --change-passphrase "${KEY_ID}"

log "When prompted, enter the new passphrase"
gpg_export_secret "${GPG_EXPORT_ARGS[@]}" "${KEY_ID}" >"gpg_private"
gpg_export_public "${GPG_EXPORT_ARGS[@]}" "${KEY_ID}" >"gpg_public"
log "Wrote private key to: $(pwd)/gpg_private"
log "Wrote public key to: $(pwd)/gpg_public"
