#!/bin/bash

CHECKSUM=md5sum

if (( $# == 1 )); then
	find "$1" -type f -printf '%P\n' | (cd "$1"; exec parallel --bar -X "$CHECKSUM {}") | sort
else
	find "$@" -type f | parallel --bar -X "$CHECKSUM {}" | sort
fi
