#!/bin/bash

. lib.sh || exit

_usage() {
	cat <<EOF
Usage: $0 PKGBUILD-DIR
EOF
}

[[ $# == 1 && -d $1 && -f $1/PKGBUILD ]] || usage

DIR="$1"
PKGBUILD="$DIR/PKGBUILD"
SRCINFO="$DIR/.SRCINFO"

do_mksrcinfo() (
	if [[ ! -e $1/.SRCINFO || $1/PKGBUILD -nt $1/.SRCINFO ]]; then
		cd "$1" && mksrcinfo
	fi
)


declare -A filename_to_arch
sed_expr=()
 
do_mksrcinfo "$DIR"
cat "$SRCINFO" | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
	filename="${link##*/}"
	filename_to_arch["$filename"]="$arch"
done

cat "$SRCINFO" | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
	echo "${link}.sha256"
done | parallel curl -fsSL | while read sha256sum filename; do
	filename="${filename#\*}"
	arch="${filename_to_arch[$filename]}"
	sed_expr+=(
		-e "s|(sha256sums_$arch)=.*|\1=('$sha256sum')|"
	)

done

trace sed -r "${sed_expr[@]}" -i "$PKGBUILD"
do_mksrcinfo "$DIR"
