#!/bin/bash

. lib.sh || exit

_usage() {
	cat <<EOF
Usage: $0 [PKGBUILD-DIR]
EOF
}

case "$#" in
0) DIR=. ;;
1) DIR="$1" ;;
*) usage "Expected 0 or 1 arguments, got $#" ;;
esac

[[ -d "$DIR" && -f "$DIR/PKGBUILD" ]] || usage "Invalid directory: $DIR"
cd "$DIR"

declare -A filename_to_arch
sed_expr=()
 
mksrcinfo
cat .SRCINFO | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
	filename="${link##*/}"
	filename_to_arch["$filename"]="$arch"
done

cat "$SRCINFO" | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
	echo "${link}.sha256"
done | parallel curl -fsSL | while read sha256sum filename; do
	filename="${filename#\*}"
	arch="${filename_to_arch[$filename]}"
	sed_expr+=(
		-e "s|(sha256sums_$arch)=.*|\1=('$sha256sum')|"
	)

done

trace sed -r "${sed_expr[@]}" -i "$PKGBUILD"
do_mksrcinfo "$DIR"
