#!/bin/bash

. lib.sh || exit

set -x

_usage() { echo "Usage: $0 <zip file> <zip (1) args...>"; }

ZIPFILE="$1"
shift
ZIPARGS=( "$@" )

if ! [[ -n $ZIPFILE && -f $ZIPFILE ]]; then
	die "Invalid zipfile: $ZIPFILE"
fi

tempdir=
cleanup() {
	rm -rf "$tempdir"
	trap - EXIT
}
trap cleanup EXIT
tempdir="$(mktemp -d)"

origdir="$PWD"
zippath="$(realpath --strip -- "$ZIPFILE")"

cd "$tempdir"
#UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE unzip -UU "$zippath"
7zz x "$zippath"
touch -r "$zippath" .

if [[ ${ZIPARGS[0]} == tar ]]; then
	newpath="${zippath%.zip}.tar"
	"${ZIPARGS[@]}" -cf "$newpath.new.$$" .
else
	newpath="$zippath"
	zip -r "${ZIPARGS[@]}" "$newpath.new.$$" .
fi

cd "$origdir"
cleanup

touch -r "$zippath" "$newpath.new.$$"
#mv "$zippath" "$zippath~"
mv "$newpath.new.$$" "$newpath"
