#!/bin/bash

VENDOR_UUID="4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"
CURRENT_ENTRY_VAR="LoaderEntrySelected"
NEXT_ENTRY_VAR="LoaderEntryOneShot"

set -e

CURRENT_ENTRY="$(efivar-crud read "$CURRENT_ENTRY_VAR-$VENDOR_UUID")"
NEXT_ENTRY_VARIANT="$1"

echo "Current booted entry is '$CURRENT_ENTRY'." >&2

readarray -t POSSIBLE_ENTRIES < <(find /boot/loader/entries -mindepth 1 -maxdepth 1 -type f -iname "$(< /etc/machine-id)-*.conf" | sed -re 's|\.conf$||' | grep -v '+' | xargs -n1 basename)
POSSIBLE_ENTRIES_NAMES=()

for entry in "${POSSIBLE_ENTRIES[@]}"; do
	case "$entry" in
	"${CURRENT_ENTRY%+*}")
		POSSIBLE_ENTRIES_NAMES+=( "$entry (*)" )
		;;
	*)
		POSSIBLE_ENTRIES_NAMES+=( "$entry" )
		;;
	esac
done

select NEXT_ENTRY in "${POSSIBLE_ENTRIES_NAMES[@]}"; do
	if ! [[ "$NEXT_ENTRY" ]]; then
		echo "E: invalid entry selected." >&2
	else
		NEXT_ENTRY="${POSSIBLE_ENTRIES[$REPLY-1]}"
		break
	fi
done

if [[ "$NEXT_ENTRY_VARIANT" ]]; then
	echo "Next variant to boot is '$NEXT_ENTRY_VARIANT'."
	NEXT_ENTRY+="+$NEXT_ENTRY_VARIANT"
fi

echo "Next booted entry will be '$NEXT_ENTRY'."

efivar-crud --attrs "non-volatile:runtime-access:boot-service-access" write "$NEXT_ENTRY_VAR-$VENDOR_UUID" "$NEXT_ENTRY"
