#!/bin/bash
alias grm='git rebase -i master'
alias grc='git rebase --continue'
alias gra='git rebase --abort'
alias gca='git commit --amend -a'
alias gc='git commit -a'
alias gr='git reset HEAD^'
alias gs='git status'
alias gd='git diff'
alias gco='git-cola'
alias gk='gitk --all'
alias gl='git log'
alias gsl='git stash list'
alias gss='git stash save'
alias gsa='git stash apply'
alias gsp='git stash pop'
alias gsd='git stash drop'
