#!/bin/bash

[ -r "$1" ] || { echo "Cannot read $1; aborting" >&2; exit 1; }

dbg() {
	[[ "$DEBUG" ]] && echo "DEBUG: $*" >&2
}

dbg_var() {
	dbg "$1: $(eval echo '$'$1)"
}

SRCPATH=$(realpath $1)
PATCHNAME=${SRCPATH##/}
PATCHNAME=${PATCHNAME//\//_}
TMPFILE=/tmp/${PATCHNAME}.tmp
PATCHFILE=/tmp/${PATCHNAME}.patch

dbg_var SRCPATH
dbg_var PATCHNAME
dbg_var TMPFILE

cp $SRCPATH $TMPFILE
${EDITOR:-vim} $TMPFILE

if ! diff -q $SRCPATH $TMPFILE 2>/dev/null >&2 ; then
	diff -u $SRCPATH $TMPFILE > $PATCHFILE

	echo "Patch file: $PATCHFILE"
	
	if [ -w "$SRCPATH" -a -z "$KEEP" ]; then
		echo "Copying new version to replace"
		cp $TMPFILE $SRCPATH
	fi
else
	echo "$TMPFILE unchanged, not generating patch"
fi

rm $TMPFILE
