#!/bin/bash

BASEDIR=$(readlink ~/Музыка/Local)
MPG=$(which mpg123)
TMPFILE="/tmp/playlist.tmp"
[ -x $MPG ] || { echo "mpg123 not available!" 2>&1; exit 1; }
[ -d $BASEDIR ] || { echo "Basedir is not available!" 2>&1; exit 1; }

rm -f $TMPFILE
touch $TMPFILE
[ -w $TMPFILE ] || { echo "Cannot write to tmpfile!" 2>&1; exit 1; }

#SWITCHES="--cpu SSE"
PLAY_MODE="-Z --loop 2 -C"

echo Switches:  $SWITCHES
echo Play mode: $PLAY_MODE
echo Base dir:  $BASEDIR

for argument in "$@"; do
	find $BASEDIR -ipath '*'"$argument"'*' >> $TMPFILE
done

cat $TMPFILE

mpg123 $SWITCHES $PLAY_MODE -@ $TMPFILE
