#!/bin/bash

vncviewer \
	-FullScreen=1 \
	-PasswordFile=$HOME/.vnc/passwd \
	-MenuKey=Insert \
	-PreferredEncoding=Tight \
	-AutoSelect=0 \
	-FullColor=0 \
	-LowColorLevel=1 \
	-QualityLevel=8 \
	-DotWhenNoCursor \
	"$@"
