#!/bin/bash

if [[ ${BATMANPREVIEW+set} ]]; then
	args=( --color=always --paging=never --wrap=auto )
else
	args=( --paging=always --wrap=never )
fi

if [[ ${MANWIDTH+set} ]]; then
	args+=( --terminal-width="$MANWIDTH" )
fi

# try not to leave a shell hanging around
# https://unix.stackexchange.com/a/778258/21885
shopt -s lastpipe
trap '' CHLD
col -bx | exec bat --language=man --style=plain "${args[@]}"
