#!/bin/bash

set -eo pipefail
shopt -s lastpipe

log() {
	echo ":: $*" >&2
}

err() {
	echo "E: $*" >&2
}

die() {
	err "$@"
	exit 1
}

usage() {
	if (( $# )); then
		echo "${0##*/}: $*" >&2
		echo >&2
	fi
	_usage >&2
	exit 1
}

_usage() {
	cat <<EOF
Usage: ${0##*/} [-Xno-skip-vcs] [FD-OPTIONS...] <PATHS...>
Options:
	-Xno-skip-vcs	do not apply heuristic to skip .git detection at \$HOME
			(i.e. always honor .gitignore according to fd(1) rules)

Any single-argument dashed options will be forwarded to fd(1).
fd(1) will be started with a '.' (match anything) pattern prepended to
the provided search paths, as the intention here is to gather completions
for further filtering.
EOF
}


#
# main
#

# NOTE the double negative here: "ignore git repo" means
# "do not use its settings", i. e. "ignore its .gitignore"
__fzf_compgen_skip_vcs_at() {
	local git_toplevel_dir
	# do not use gitignore from $HOME
	if (( fd_try_skip_vcs )) \
	   && git_toplevel_dir="$(git -C "$1" rev-parse --show-toplevel 2>/dev/null)" \
	   && [[ "$git_toplevel_dir" == "$HOME" ]]; then
		return 0
	fi
	return 1
}

__fzf_compgen_nofollow_at() {
	# do not follow symlinks under /sys
	if [[ $1/ == /sys/* ]]; then
		return 0
	fi
	return 1
}

__fzf_compgen_fd() {
	local relpath="${1-.}"
	local abspath="$(realpath -q "$relpath")"

	# fd_opts declared in parent scope
	fd_opts+=( --hidden --exclude ".git" )
	if ! __fzf_compgen_nofollow_at "$abspath"; then
		fd_opts+=( --follow )
		# hack: do not follow Wine's `Z:` back to `/`
		fd_opts+=( --exclude '**/dosdevices/z:/*')
	fi
	if __fzf_compgen_skip_vcs_at "$abspath"; then
		fd_opts+=( --no-ignore-vcs --no-ignore-parent )
	fi
	exec fd "${fd_opts[@]}" . "${fd_paths[@]}"
}

case "$#" in
0) usage ;;
*) ;;
esac

fd_opts=()
fd_paths=()
fd_try_skip_vcs=1

while (( $# )); do
	case "$1" in
	-Xno-skip-vcs) fd_try_skip_vcs=0 ;;
	-*) fd_opts+=( "$1" ) ;;
	*) break ;;
	esac
	shift
done

if (( $# )); then
	fd_paths=( -- "$@" )
fi

__fzf_compgen_fd "$@"
