#!/bin/bash

ARIA2_OPTIONS=(
	# general behavior
	--file-allocation=trunc
	--enable-mmap=false
	--stderr=true

	# bittorrent behavior
	--follow-torrent=true
	--bt-save-metadata=true
	--bt-load-saved-metadata=true
	--bt-detach-seed-only=true
	--seed-time=1
	--enable-dht{,6}=true
	--enable-peer-exchange=true
	--dht-listen-port=40090-40099
	--listen-port=40090-40099

	# transparent conditional re-fetch (HTTP)
	--allow-overwrite=true
	--auto-file-renaming=false
	--conditional-get=true
	--remote-time=true

	# transparent conditional re-fetch (bittorrent)
	--check-integrity=true
	--bt-hash-check-seed=false
	--allow-piece-length-change=true
)

set -x
exec /usr/bin/aria2c \
	"${ARIA2_OPTIONS[@]}" \
	"$@"
