#!/bin/bash

ARIA2_OPTIONS=(
	# general behavior
	--file-allocation=trunc
	--enable-mmap=false
	--stderr=true

	# transparent conditional re-fetch (HTTP)
	--allow-overwrite=true
	--auto-file-renaming=false
	--conditional-get=true
	--remote-time=true
)

set -x
exec /usr/bin/aria2c \
	--allow-piece-length-change=true \
	"${ARIA2_OPTIONS[@]}" \
	"$@"
