#!/bin/bash

set -eo pipefail
shopt -s lastpipe
shopt -s extglob

bscalc "$@" | readarray -t response
case "${#response[@]}" in
0) ;;
1) printf "%s\n" "${response%%+([a-zA-Z ])}"; exit 0 ;;
*) printf >&2 "%s\n" "${response[@]}" ;;
esac
exit 1
