#!/bin/bash -e

BTRFS_SUB_DEL_ARGS=()
BTRFS_SUB_FIND_ARGS=()

for arg; do
	case "$arg" in
	-c|--commit-after|-C|--commit-each|-v|--verbose|-q|--quiet)
		BTRFS_SUB_DEL_ARGS+=( "$arg" ) ;;
	*)
		BTRFS_SUB_FIND_ARGS+=( "$arg" ) ;;
	esac
done

btrfs-sub-find "${BTRFS_SUB_FIND_ARGS[@]}" | tac | xargs -r btrfs sub del "${BTRFS_SUB_DEL_ARGS[@]}"
