#!/bin/bash

set -eo pipefail
shopt -s lastpipe

# shellcheck source=../inc/-mktempdir-main
. -- -mktempdir-main


#
# main
#

setup_tmpdir "." "$TMP_ROOT"

if [[ -e x.py && (-e config.toml || -e config.example.toml) ]]; then
	# rustc
	tomlq <config.toml -r '.build["build-dir"] // empty' | IFS= read -r build_dir ||:
	process_one_dir "${build_dir:-"build"}"
else
	process_one_dir "target"
fi
