#!/bin/bash

set -eo pipefail
shopt -s lastpipe

#
# constants
#

CARGO=(
	/usr/bin/cargo
)

CARGO_CONFIG=


#
# functions
#

try_config() {
	local arg="$1"
	if [[ -e "$arg" ]]; then
		CARGO_CONFIG="$arg"
		return
	fi
	return 1
}

try_configs() {
	local arg
	for arg; do
		if try_config "$HOME/.cargo/config-$arg.toml"; then
			return
		fi
	done
}

call_cargo() {
	local -a args=( "$@" )
	local -a cmd

	cmd+=( "${CARGO[@]}" )
	if [[ $CARGO_CONFIG ]]; then
		cmd+=( --config "$CARGO_CONFIG" )
	fi
	cmd+=( "${args[@]}" )

	set -x
	exec "${cmd[@]}"
}


#
# main
#

args=()
profile=

while (( $# )); do
	case "$1" in
	run|build|check|rustc) profile=dev ;;
	test) profile=test ;;
	bench) profile=bench ;;
	install) profile=release ;;

	--profile) profile="$2" ;;
	--profile=) profile="${1#--profile=}" ;;

	--release) profile=release ;;
	--dev) profile=dev ;;

	# if we got to --, there won't be any parsable arguments, bail
	--) break ;;
	esac

	args+=( "$1" )
	shift
done

case "$profile" in
bench|release)   try_configs "$profile" "release" ;;
dev|test|"")     try_configs "$profile" "dev" ;;
# TODO parse the profile to find out what it inherits from?
rel-*|release-*) try_configs "$profile" "release" ;;
*) ;;
esac

call_cargo "${args[@]}" "$@"
