#!/bin/bash

# `rg` is in a pipeline and therefore cannot autodetect terminal capabilities
# therefore, perform sunrise by hand
color=()
if [[ -t 1 ]]; then
	color=(--color=always)
fi

rg -uuu --no-heading --no-line-number --field-match-separator=$'\t' "${color[@]}" . "$@" \
	| sort -t $'\t' -k1 \
	| column -s $'\t' -t -l2
