#!/bin/bash -e

loadflags() (
  . /etc/makepkg.conf &>/dev/null
  # as we are hardcoding debug, do this also
  CFLAGS+=" $DEBUG_CFLAGS"
  CXXFLAGS+=" $DEBUG_CXXFLAGS"
  { declare -p CC CXX CPPFLAGS CFLAGS CXXFLAGS LDFLAGS | sed -nr "s|^declare (-[^ ]+ )+|export |p"; } 2>/dev/null
)

eval "$(loadflags)"
exec cmake \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Debug \
  "$@"
