#!/bin/bash

BASE_DIR=~/tmp/big/flatpak-builder

: "${FLATPAK_BUILDER_REPO="$BASE_DIR/repo"}"
: "${FLATPAK_BUILDER_CACHE="$BASE_DIR/state"}"
: "${FLATPAK_BUILDER_APP="$BASE_DIR/app"}"

mkdir -p "$FLATPAK_BUILDER_REPO" "$FLATPAK_BUILDER_CACHE" "$FLATPAK_BUILDER_APP"

FLATPAK_BUILDER_ARGS=()
if [[ ${FLATPAK_BUILDER_KEY+set} ]]; then
	FLATPAK_BUILDER_ARGS=(
		--gpg-sign="$FLATPAK_BUILDER_KEY"
	)
fi

APP_DIR="$(mktemp -d -p "$FLATPAK_BUILDER_APP")"
cleanup() {
	rm -rf "$APP_DIR"
}
trap cleanup EXIT

/usr/bin/flatpak-builder \
	--user \
	--install-deps-from=flathub \
	"${FLATPAK_BUILDER_ARGS[@]}" \
	--ccache \
	--state-dir "$FLATPAK_BUILDER_CACHE" \
	--repo "$FLATPAK_BUILDER_REPO" \
	"$APP_DIR" \
	"$@"
