#!/bin/bash

BASE_DIR=~/tmp/big/flatpak-builder
mkdir -p "$BASE_DIR"/{state,repo,app}

APP_DIR="$(mktemp -d -p ~/tmp/big/flatpak-builder/app)"
cleanup() {
	rm -rf "$app_dir"
}
trap cleanup EXIT

/usr/bin/flatpak-builder \
	--gpg-sign='31EFDDC98A18FA610D389A3D281015BE2CAC2CBC' \
	--ccache \
	--state-dir "$BASE_DIR/state" \
	--repo "$BASE_DIR/repo" \
	"$APP_DIR" \
	"$@"
