#!/bin/bash

set -eo pipefail
shopt -s lastpipe

if [[ -w /dev/cpu_dma_latency ]]; then
	exec {cpu_dma_latency_fd}>/dev/cpu_dma_latency
	printf "%b" '\x00\x00\x00\x00' >&$cpu_dma_latency_fd
fi

exec "$@"
