#!/bin/bash

export LD_PRELOAD=/usr/lib/libjemalloc.so
export MALLOC_CONF=abort_conf:true,background_thread:true,metadata_thp:always,thp:always,dirty_decay_ms:1000,muzzy_decay_ms:1000,narenas:1

exec "$@"
