#!/bin/bash


exec make \
	KCFLAGS="-ffile-prefix-map=$PWD=." \
	SOURCE_DATE_EPOCH=0 \
	KBUILD_BUILD_TIMESTAMP="$(date -Ru -d '@0')" \
	KBUILD_BUILD_HOST=archlinux \
	KBUILD_BUILD_USER=linux \
	-j$(nproc) \
	"$@"
