#!/bin/bash

vars=()
if [[ -e version ]]; then vars+=(
	KERNELRELEASE="$(< version)"
); fi

	# KCFLAGS="-ffile-prefix-map=$PWD=. -ffile-prefix-map=./=" \
exec make \
	KCFLAGS="-ffile-prefix-map=$PWD=." \
	SOURCE_DATE_EPOCH=0 \
	KBUILD_BUILD_TIMESTAMP="$(date -Ru -d '@0')" \
	KBUILD_BUILD_HOST=archlinux \
	KBUILD_BUILD_USER=linux \
	"${vars[@]}" \
	-j$(nproc) \
	"$@"
