#!/bin/bash

#
# AFAIU real mksrcinfo (pkgbuild-introspection) actually is long in status of
# "unmaintained prototype" (with package dropped to AUR), with its functionality
# copied into makepkg(8) albeit in a very much less usable form.
#

if command -v aur &>/dev/null; then
	exec aur build--pkglist --srcinfo > .SRCINFO
else
	exec makepkg --printsrcinfo > .SRCINFO
fi

