#!/bin/bash

#
# AFAIU real mksrcinfo (pkgbuild-introspection) actually is long in status of
# "unmaintained prototype" (with package dropped to AUR), with its functionality
# copied into makepkg(8) albeit in a very much less usable form.
#

if ! [[ .SRCINFO -ot PKGBUILD ]]; then
	exit 0
fi

if [[ -x /usr/lib/aurutils/aur-build--pkglist ]]; then
	exec /usr/lib/aurutils/aur-build--pkglist --srcinfo
else
	exec makepkg --printsrcinfo
fi | sponge .SRCINFO

