#!/bin/bash

#
# AFAIU real mksrcinfo (pkgbuild-introspection) actually is long in status of
# "unmaintained prototype" (with package dropped to AUR), with its functionality
# copied into makepkg(8) albeit in a very much less usable form.
#

if [[ -x /usr/lib/aurutils/aur-build--pkglist ]]; then
	exec /usr/lib/aurutils/aur-build--pkglist --srcinfo > .SRCINFO
else
	exec makepkg --printsrcinfo > .SRCINFO
fi

