#!/bin/bash

exec podman run \
	--volume /var/cache/pacman/pkg:/var/cache/pacman/pkg:rw \
	--volume "$HOME"/bin/etc/pacman.conf:/etc/pacman.conf:ro \
	--volume /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist:ro \
	"$@"
