#!/bin/sh

# Script version of my very useful alias `r-sync-put` that rsyncs files into the destination
# preserving only times (i. e. applying correct perms/ACLs for the destination).
# "Sync" variant (i.e. delete files in dest/ absent from src/)

exec rsync -r --partial --no-i-r -ltDH --chmod=ugo=rwX --delete "$@"
