#!/bin/bash

XATTR=( --xattr-read --xattr-write --hash-unmatched )
for arg; do
	case "$arg" in
	--xattr-read|--xattr-clear)
		# drop implied --xattr-read
		# this messes up indices, but it doesn't matter for "${XATTR[@]}"
		unset XATTR[0] ;;
	esac
done

exec rmlint -T df -Dj -o progressbar -o json:rmlint.json -o sh:rmlint.sh -o pretty -o summary -c sh:handler=remove --hidden "${XATTR[@]}" "$@"
