#!/bin/bash

IFS=':'
read -ra path <<<"$PATH"
ipath=()
for p in "${path[@]}"; do
	case "$p" in
	/usr/*) ipath+=("$p") ;;
	/opt/*) ipath+=("$p") ;;
	esac
done
IPATH="${ipath[*]}"
unset IFS

vars=(
	SSH_AUTH_SOCK
	"${!CCACHE_@}"
	"${!DISTCC_@}"
	RUSTC_WRAPPER
)

ARG_ISOLATE=1
while (( $# )); do
	case "$1" in
	--no-isolate) shift; ARG_ISOLATE=0 ;;
	--isolate)    shift; ARG_ISOLATE=1 ;;
	*)            break ;;
	esac
done

if (( ARG_ISOLATE )); then
	# "isolate": pass a sanitized $PATH and no more variables
	vars+=(
		PATH="$IPATH"
	)
else
	# "do not isolate": pass full $PATH and all relevant variables
	unset vars[-1]  # drop RUSTC_WRAPPER, re-added below
	vars+=(
		PATH
		CC CXX
		CFLAGS CXXFLAGS LDFLAGS
		RUSTFLAGS "${!RUSTC_@}" "${!CARGO_@}"
		GOFLAGS "${!CGO_@}"
		GOMODCACHE
	)
fi


args=()
for var in "${vars[@]}"; do
	args+=( -E "$var" )
done

set -x
exec systemd-run-here \
	-p User="${SUDO_USER-$(id -un)}" \
	-p Slice=system-cpu.slice \
	-p CPUSchedulingPolicy=batch \
	-p Nice=18 \
	"${args[@]}" \
	"$@"
