#!/bin/bash

IFS=':'
read -ra path <<<"$PATH"
ipath=()
for p in "${path[@]}"; do
	case "$p" in
	/usr/*) ipath+=("$p") ;;
	/opt/*) ipath+=("$p") ;;
	esac
done
IPATH="${ipath[*]}"
unset IFS

vars=(
	SSH_AUTH_SOCK
	"${!CCACHE_@}"
	"${!DISTCC_@}"
	PATH="$IPATH"
)

args=()
for var in "${vars[@]}"; do
	args+=( -E "$var" )
done

set -x
exec systemd-run-here \
	-p User="${SUDO_USER-$(id -un)}" \
	-p Slice=system-cpu.slice \
	-p CPUSchedulingPolicy=batch \
	-p Nice=18 \
	"${args[@]}" \
	"$@"
