#!/bin/bash

ALL=(
  Core
  CPU
  Busy%
  Avg_MHz
  Bzy_MHz
  GFXMHz
  GFXAMHz

  IPC
  IRQ
  Totl%C0
  Any%C0
  GFX%C0
  CPUGFX%
  Pkg%pc2
  Pkg%pc3
  Pkg%pc6
  Pkg%pc7
  Pkg%pc8
  Pkg%pc9
  Pk%pc10
  CPU%LPI
  SYS%LPI

  UncMHz
  Die%c6

  PkgWatt
  CorWatt
  GFXWatt
  RAMWatt
  SysWatt

  CoreThr
  CoreTmp
  PkgTmp
)

IFS=,
columns="${ALL[*]}"
IFS=

exec turbostat -s "$columns" "$@"
