#!/bin/bash

GREP_CMD=()

vimgrep_rg() {
	GREP_CMD=( "$1" --vimgrep "${@:2}" )
}

vimgrep_git_grep() {
	# we need to pass `--line-number --column` to `git grep`, however:
	# - `grep` may not necessarily happen immediately after `git`, so we can't prepend the flags
 	# - `grep` may end with `--` and paths, so we can't append the flags either
	# - the only way is to pass them as git-config options on the command line,
	#   which we can do immediately after `git`
	GREP_CMD=( "$1" -c grep.lineNumber=true -c grep.column=true "${@:2}" )
}

vimgrep_grep() {
	GREP_CMD=( "$1" --with-filename --line-number --column "${@:2}" )
}

if [[ "${1##*/}" == rg ]]; then
	vimgrep_rg "$@"
elif [[ "${1##*/}" == git ]]; then
	vimgrep_git_grep "$@"
elif [[ "${1##*/}" == grep ]]; then
	vimgrep_grep "$@"
else
	if command -v git &>/dev/null && [[ "$(git rev-parse --is-inside-work-tree)" == "true" ]]; then
		vimgrep_git_grep git grep "$@"
	elif command -v rg &>/dev/null; then
		vimgrep_rg rg "$@"
	else
		vimgrep_grep grep "$@"
	fi
fi

exec vim -c copen -q <("${GREP_CMD[@]}")
