#!/bin/bash -e

SCRIPT_NAME="${0##*/}"
case "$SCRIPT_NAME" in
#xfreerdp)
#	APP_NAME="$BUILD_DIR/client/X11/xfreerdp" ;;
#wlfreerdp)
#	APP_NAME="$BUILD_DIR/client/Wayland/wlfreerdp" ;;
#sdlfreerdp)
#	APP_NAME="$BUILD_DIR/client/SDL/sdl-freerdp" ;;
xfreerdp|wlfreerdp)
	APP_NAME="/usr/bin/$SCRIPT_NAME" ;;
*)
	APP_NAME="/usr/bin/xfreerdp" ;;
esac

OPTIONS=(
	/size:2560x1440
	/dynamic-resolution
	/scale:140
	/sound:sys:pulse
	/floatbar:show:fullscreen
	+auto-reconnect
)

OPTIONS_BEST=(
	/network:auto

	# XXX: for some reason Win10 prefers progressive to avc, so do not advertise it
	# XXX: order matters with freerdp 2.10 (not in master)
	/gfx:rfx,avc420,avc444
	/rfx-mode:video
	/gdi:hw
)

OPTIONS_FASTEST=(
	-aero
	-themes
	-wallpaper
	-fonts
	-window-drag
	-menu-anims
	/bpp:8
	+compression
	/compression-level:2
	/codec-cache:rfx
	#+bitmap-cache  # freerdp 2.x
	#+glyph-cache  # freerdp 2.x
	#+offscreen-cache  # freerdp 2.x
	/cache:codec:rfx,bitmap:on,glyph:on,offscreen:on  # freerdp 3.0
	/network:modem

	# XXX: for some reason Win10 prefers progressive to avc, so do not advertise it
	# XXX: order matters with freerdp 2.10 (not in master)
	/gfx:rfx,avc420,avc444
	/rfx-mode:video
	/gdi:hw

	#/rfx # RemoteFxCodec
	#/gfx:rfx # RemoteFxCodec
	#/gfx:progressive # GfxProgressive
	#/gfx:avc420 # GfxH264
	#/gfx:avc444 # GfxAVC444
	#+gfx-progressive # == /gfx:progressive
	#-gfx-thin-client # == /gfx:thin-client, implies /gfx:small-cache
	#-gfx-small-cache # == /gfx:small-cache
)

ARGS=()
for arg; do
	# replace some args
	case "$arg" in
	/best)
		ARGS+=( "${OPTIONS_BEST[@]}" ) ;;
	/fast|/fastest|/worst)
		ARGS+=( "${OPTIONS_FASTEST[@]}" ) ;;
	*)
		ARGS+=( "$arg" ) ;;
	esac
	# augment some args
	case "$arg" in
	/u:intelfx|/u:intelfx@intelfx.name)
		ARGS+=( /admin )
		ARGS+=( -sec-nla ) # xfreerdp 2.10
		# ARGS+=( /sec:nla:off ) # xfreerdp 3.0
		;;
	esac
	shift
done

set -x
exec "$APP_NAME" "${OPTIONS[@]}" "${ARGS[@]}"
