#!/bin/bash

set -eo pipefail
shopt -s lastpipe

SCRIPT_NAME="${0##*/}"
case "$SCRIPT_NAME" in
sdlfreerdp)
	SCRIPT_NAME="sdl-freerdp" ;&
xfreerdp|wlfreerdp)
	APP_NAME="/usr/bin/${SCRIPT_NAME}3" ;;
*)
	APP_NAME="/usr/bin/xfreerdp" ;;
esac

OPTIONS=(
	/size:2560x1440
	/dynamic-resolution
	/scale:140
	/sound:sys:pulse
	/floatbar:show:fullscreen
	+auto-reconnect
)

OPTIONS_BEST=(
	/network:auto

	# XXX: for some reason Win10 prefers progressive to avc, so do not advertise it
	# XXX: order matters with freerdp 2.10 (not in master)
	/gfx:rfx,avc420,avc444
	/rfx-mode:video
	/gdi:hw
)

OPTIONS_FASTEST=(
	-aero
	-themes
	-wallpaper
	-fonts
	-window-drag
	-menu-anims
	/bpp:8
	+compression
	/compression-level:2
	#/codec-cache:rfx  # freerdp 2.x
	#+bitmap-cache  # freerdp 2.x
	#+glyph-cache  # freerdp 2.x
	#+offscreen-cache  # freerdp 2.x
	/cache:codec:rfx,bitmap:on,glyph:on,offscreen:on  # freerdp 3.0
	/network:modem

	# XXX: for some reason Win10 prefers progressive to avc, so do not advertise it
	# XXX: order matters with freerdp 2.10 (not in master)
	/gfx:rfx,avc420,avc444
	/rfx-mode:video
	/gdi:hw

	#/rfx # RemoteFxCodec
	#/gfx:rfx # RemoteFxCodec
	#/gfx:progressive # GfxProgressive
	#/gfx:avc420 # GfxH264
	#/gfx:avc444 # GfxAVC444
	#+gfx-progressive # == /gfx:progressive
	#-gfx-thin-client # == /gfx:thin-client, implies /gfx:small-cache
	#-gfx-small-cache # == /gfx:small-cache
)

ARGS=()
for arg; do
	# replace some args
	case "$arg" in
	/best)
		ARGS+=( "${OPTIONS_BEST[@]}" ) ;;
	/fast|/fastest|/worst)
		ARGS+=( "${OPTIONS_FASTEST[@]}" ) ;;
	*)
		ARGS+=( "$arg" ) ;;
	esac
	case "$arg" in
	/v:*) ARG_HOST="${arg#"/v:"}" ;;
	/u:*) ARG_USER="${arg#"/u:"}" ;;
	/p:*) ARG_PASS_SET=1 ;;
	esac
	# augment some args
	case "$arg" in
	/u:intelfx|/u:intelfx@intelfx.name)
		ARGS+=( /admin )
		ARG_NO_NLA=1
		;;
	-decorations)
		ARGS+=( /floatbar:show:always )
		;;
	esac
done

if [[ ! $ARG_PASS_SET && $ARG_HOST && $ARG_USER ]]; then
	if [[ -e ~/.password-store/misc/rdp/$ARG_HOST/$ARG_USER.gpg ]]; then
		ARG_PASS_COMMAND=(pass "misc/rdp/$ARG_HOST/$ARG_USER")
	fi
fi

if [[ $ARG_PASS_SET ]]; then
	:
elif [[ $ARG_PASS_COMMAND ]]; then
	exec < <(set -x; exec "${ARG_PASS_COMMAND[@]}")
	ARGS+=( /auth-pkg-list:'ntlm,!kerberos' /d: /from-stdin )
elif [[ $ARG_NO_NLA ]]; then
	# ARGS+=( -sec-nla ) # xfreerdp 2.10
	ARGS+=( /sec:nla:off /d: /p: ) # xfreerdp 3.0
fi

set -x
exec "$APP_NAME" "${OPTIONS[@]}" "${ARGS[@]}"
