#!/bin/sh
#
# Status output if running on terminal
#

# tar: only do this if tar is invoked in UNIX or GNU style, otherwise the parsing will break (tar won't recognize traditional style options after dashed ones)
if [[ -t 2 && "$1" == -* ]]; then
	exec /usr/bin/tar --checkpoint=1000 --checkpoint-action=ttyout=%c "$@"
else
	exec /usr/bin/tar "$@"
fi
