#!/bin/bash

config_path="$(systemd-path user-configuration)"

GTK_THEME=Adwaita # Arc

# $1: whether to enable dark (1 or 0)
function adjust_gtk3() {
	local gtk3_theme=( Adwaita Adwaita-dark ) #( Arc Arc-Dark )
	#local shell_theme=( Adwaita Adwaita ) #( Arc Arc-Dark )

	dconf write /org/gnome/desktop/interface/gtk-theme "'${gtk3_theme[$1]}'"
	#dconf write /org/gnome/shell/extensions/user-theme/name "'${shell_theme[$1]}'"
}

# $1: whether to enable dark (1 or 0)
function adjust_gedit() {
	local scheme=( solarized-light solarized-dark )

	dconf write /org/gnome/gedit/preferences/editor/scheme "'${scheme[$1]}'"
}

# $1: whether to enable dark (1 or 0)
function adjust_terminal() {
	local profiles_default=( 4b05dbdf-11e8-4f29-b788-7016ec6b6de9
	                         b739b980-6bbc-4e0c-9dda-313ad61029ff )

	# set defaults for new windows
	dconf write /org/gnome/terminal/legacy/profiles:/default "'${profiles_default[$1]}'"

	# reconfigure existing windows
	local o objects=()
	read -a objects < <(busctl --auto-start=false --list --user tree org.gnome.Terminal | grep '^/org/gnome/Terminal/window/') || return 0
	for o in "${objects[@]}"; do
		busctl --auto-start=false -j --user call org.gnome.Terminal "$o" org.gtk.Actions Activate "sava{sv}" "profile" "1" "s" "${profiles_default[$1]}" "0" || true
	done
}

# $1: whether to enable dark (1 or 0)
function adjust_builder() {
	local night_mode=( false true )
	local style_scheme_name=( solarized-light solarized-dark )

	dconf write /org/gnome/builder/night-mode "${night_mode[$1]}"
	dconf write /org/gnome/builder/editor/style-scheme-name "'${style_scheme_name[$1]}'"
}

# $1: whether to enable dark (1 or 0)
function adjust_kde() {
	local kdeglobals=( light dark )
	local icon_theme=( breeze breeze-dark )

	# Configure Breeze
	cp -a "$config_path/kdeglobals-${kdeglobals[$1]}" "$config_path/kdeglobals"
	if command -v kbuildsycoca5 &>/dev/null; then
		kbuildsycoca5
	fi

	# Configure qt5ct
	sed -re "s|^icon_theme=.*|icon_theme=${icon_theme[$1]}|" -i "$config_path/qt5ct/qt5ct.conf"
}

# $1: whether to enable dark (1 or 0)
function adjust_kate() {
	local schema=( "Solarized (light)" "Solarized (dark)" )

	sed -re "s|^Schema=.*|Schema=${schema[$1]}|" -i "$config_path/katepartrc"
}

MODE=()

case "${1:-1}" in
	dark|on|1) MODE=(1) ;;
	light|off|0) MODE=(0) ;;
	*) echo "E: unknown mode: '$1'" >&2; exit 1 ;;
esac
shift

if (( ! $# )); then
	set -- "$@" gtk3 gedit terminal builder kde kate
fi

for arg; do
	"adjust_$arg" "${MODE[@]}"
done
