#!/bin/bash

. lib.sh || exit

_usage() {
  cat <<EOF
Usage: ${0##*/} [-n|--dry-run] [-v|--verbose] [-f|--fs|--filesystem|--filesystems] [-F|--free-space] <block device...>

Attempt to discard all unused space within a disk or a disk image.

Free space within (recognized) filesystems will be discarded by way of mounting
the filesystem with \`-o discard\` and running \`fstrim\` on it.

Unpartitioned space will be discarded by parsing the partition table and issuing
\`blkdiscard\` commands for all contiguous regions not allocated to a partition.

Additionally, this command may run \`blkdiscard\` against all partitions that
do not contain a (recognized) filesystem. WARNING -- THIS WILL DESTROY ALL DATA
ON SUCH PARTITIONS.

	-f, --filesystems	Discard free space within recognized filesystems
	-F, --free-space	Discard unpartitioned space
	--destroy-unknown	(DANGEROUS) Discard partitions without a
				recognized filesystem
	-n, --dry-run		Do not actually perform any modifications
				(implies --verbose)
	-v, --verbose		Print commands that are executed
EOF
}

run() {
	if (( ARG_DRY_RUN || ARG_VERBOSE )); then
		echo "+ $*" >&2
	fi
	if ! (( ARG_DRY_RUN )); then
		eval "$*"
	fi
}

run_always() {
	if (( ARG_DRY_RUN || ARG_VERBOSE )); then
		echo "+ $*" >&2
	fi
	eval "$*"
}

disk_fstrim() {
	eval "$(ltraps)"

	if ! [[ -f "$disk" || -b "$disk" ]]; then
		err "$disk: invalid disk, expected a file or a block device"
		(( ++errs ))
		return
	fi

	local rdisk="$disk" disk="$disk" loop
	if ! [[ -b "$disk" ]]; then
		if ! loop="$(run_always losetup -Pf --show "$disk")" || ! [[ $loop ]]; then
			err "$disk: failed to set up a loop device"
			(( ++errs ))
			return
		fi
		ltrap "run_always losetup -d '$loop'"
		log "$disk: configured a loopback device at $loop"
		disk="$loop"
	fi

	local pttype fstype
	pttype="$(blkid -o value -s PTTYPE "$disk")"
	fstype="$(blkid -o value -s TYPE "$disk")"
	local partitions=()

	if [[ "$pttype" ]]; then
		find "$disk"p[0-9]* | readarray -t partitions
		log "$rdisk: whole disk detected ($pttype), discovered ${#partitions[@]} partitions"
	elif [[ "$fstype" ]]; then
		partitions=( "$disk" )
		log "$rdisk: filesystem detected ($fstype), treating as a partition"
	else
		err "$rdisk: could not find a partition table or a filesystem signature, skipping"
		(( ++errs ))
		return
	fi

	if (( ARG_TRIM_FILESYSTEMS )); then
		log "$rdisk: trimming free space on ${#partitions[@]} filesystems"
		local part rpart
		for part in "${partitions[@]}"; do
			rpart="$part"
			if [[ $rdisk != "$disk" ]]; then
				rpart="$rdisk(${part#"$disk"})"
			fi
			part_fstrim || (( ++errs ))
		done
		sync
	fi

	if (( ARG_TRIM_FREE_SPACE )); then
		disk_pttrim || (( ++errs ))
		sync
	fi
}

part_fstrim() {
	eval "$(ltraps)"

	local fstype
	fstype="$(blkid -o value -s TYPE "$part")"
	if ! [[ "$fstype" ]]; then
		if ! (( ARG_TRIM_UNKNOWN )); then
			warn "$rpart: could not find a filesystem signature, skipping"
			return
		fi

		warn "$rpart: could not find a filesystem signature, discarding!"
		# not using `blkdiscard --force` on purpose
		if ! run blkdiscard --verbose "$part"; then
			err "$rpart: could not run blkdiscard, skipping"
			(( ++errs ))
		fi
		return
	fi

	local uuid luks part="$part"
	if [[ $fstype == crypto_LUKS ]]; then
		uuid="$(blkid -o value -s UUID "$part")"
		if ! [[ $uuid ]]; then
			err "$rpart: could not read LUKS container UUID, skipping"
			(( ++errs ))
			return
		fi
		luks="luks-$uuid"
		if ! run cryptsetup open "$part" "$luks" --allow-discards; then
			err "$rpart: could not open LUKS container as $luks, skipping"
			(( ++errs ))
			return
		fi
		ltrap "run cryptsetup close '$luks'"
		part="/dev/mapper/$luks"
	fi

	local mount_dir="$work_dir/${part##*/}"
	ltrap "rm -d '$mount_dir'"
	mkdir -p "$mount_dir"

	local mount_opts
	case "$fstype" in
	btrfs) mount_opts="ro,discard=async" ;;
	ntfs) mount_opts="discard" ;;
	*) mount_opts="ro,discard" ;;
	esac

	ltrap "run umount '$mount_dir' || run umount -l '$mount_dir'"
	if ! run mount "$part" "$mount_dir" -o "$mount_opts"; then
		err "$rpart: could not mount at $mount_dir ($mount_opts), skipping"
		(( ++errs ))
		return
	fi

	if ! run fstrim -v "$mount_dir"; then
		err "$rpart: could not run fstrim at $mount_dir"
		(( ++errs ))
	fi
	sync
}

disk_pttrim() {
	eval "$(ltraps)"

	if ! [[ "$pttype" ]]; then
		warn "$rdisk: not a whole disk, not trimming unallocated space"
		return
	fi

	log "$rdisk: trimming unallocated free space"

	local free cmds=() FREE=()
	parted -m "$disk" unit b print free | grep -E ':free;$' | while IFS=: read -ra FREE; do
		cmds+=( "blkdiscard --force --verbose --offset '${FREE[1]%%B}' --length '${FREE[3]%%B}' '$disk'" )
		(( free += ${FREE[3]%%B} )) ||:
	done

	for c in "${cmds[@]}"; do
		if ! run "$c"; then
			err "$rdisk: could not run blkdiscard, skipping"
			(( ++errs ))
			return
		fi
	done

	log "$rdisk: trimmed $(bscalc -H "$free")"
}

#
# main
#

declare -A ARGS=(
	[-f|--fs|--filesystem|--filesystems]=ARG_TRIM_FILESYSTEMS
	[-F|--free-space]=ARG_TRIM_FREE_SPACE
	[-n|--dry-run]=ARG_DRY_RUN
	[-v|--verbose]=ARG_VERBOSE
	[--destroy-unknown]=ARG_TRIM_UNKNOWN
	[--]=DISKS
)
parse_args ARGS "$@" || usage
(( ${#DISKS[@]} )) || usage "At least one disk is required"
(( ARG_TRIM_FREE_SPACE || ARG_TRIM_FILESYSTEM )) || usage "At least one of -f/--filesystems and -F/--free-space is required"
(( ARG_TRIM_UNKNOWN )) && loud "WARNING!" "disk-fstrim will DESTROY ALL DATA on partitions it does not understand!"

eval "$(globaltraps)"

work_dir="$(mktemp -d)"
ltrap "rm -d '$work_dir'"

errs=0
for disk in "${DISKS[@]}"; do
	disk_fstrim || (( ++errs ))
done
exit $(( errs ? 1 : 0 ))
