#!/bin/bash

. lib.sh || exit

KEYS=(
	#DeviceClass
	DeviceName
	#HardwareModel
	#ModelNumber
	ProductType
	ProductVersion
)

kvpairs() {
	declare -n table="$1"
	shift

	local items=()
	local k v
	for k; do
		if [[ ${table[$k]+set} ]]; then
			items+=( "$k=${table[$k]}" )
		fi
	done
	echo "${items[*]}"
}

idevice_id --list | while read udid; do
	declare -A info
	ideviceinfo --udid "$udid" | grep -E "^($(join '|' "${KEYS[@]}")): " | while read line; do
		if [[ $line =~ ^([^ ]+):\ (.+)$ ]]; then
			info[${BASH_REMATCH[1]}]="${BASH_REMATCH[2]}"
		else
			err "$udid: bad line: '$line'"
		fi
	done

	echo "$udid (${info[DeviceName]}) [${info[ProductType]}] [${info[ProductVersion]}]"
done
