#!/bin/bash -e

. lib.sh || exit

TARGET_DIR="$1"
if ! [[ -d "$TARGET_DIR" ]]; then
	die "Bad target directory: '$TARGET_DIR'"
fi
if ! [[ -w "$TARGET_DIR" ]]; then
	die "Cannot write target directory: '$TARGET_DIR'"
fi
TAG_PATH="$TARGET_DIR/DONTBORG.TAG"
if ! [[ -e "$TAG_PATH" ]]; then
	log "Creating '$TAG_PATH'"
	cat >"$TAG_PATH" <<EOF
# This file is a negative Borg archival tag created by mkdontborgtag.
EOF
fi
