#!/bin/bash

set -eo pipefail
shopt -s lastpipe
shopt -s extglob

# shellcheck source=../lib/lib.sh
. lib.sh

_usage() {
	cat <<EOF
Usage: $0 [(--solid|--esd)[=LEVEL] | (--solid-all|--esd-all)[=LEVEL] | (--compress|--wim)[=LEVEL] | (--nocompress|--none)] [--split=MiB] [--replace|--overwrite] [FILES...]
EOF
}


#
# args
#

declare -A ARGS=(
	[--solid\|--esd::]=ARG_COMPRESS_SOLID
	[--solid-all\|--esd-all::]=ARG_COMPRESS_SOLID_FORCE
	[--compress\|--wim::]=ARG_COMPRESS
	[--nocompress\|--none]=ARG_COMPRESS_NONE
	[--replace\|--overwrite]=ARG_REPLACE
	[--filter-drop:]="ARG_FILTER_DROP split=, append"
	[--filter-keep:]="ARG_FILTER_KEEP split=, append"
	[--split:]="ARG_SPLIT"
	[--drop-oem]=ARG_DROP_OEM
	[--tmpdir:]=ARG_TMPDIR
	[-o\|--output:]=ARG_OUTPUT
	[-h\|--help]=ARG_USAGE
	[--]=ARG_FILES
)
parse_args ARGS "$@" || usage
[[ ! $ARG_USAGE ]] || usage

MKTEMPDIR=(mktemp)
if [[ ${ARG_TMPDIR+set} ]]; then
	MKTEMPDIR+=( "--tmpdir=$ARG_TMPDIR" )
fi
mktempdir() {
	"${MKTEMPDIR[@]}" "$@"
}

COMPRESS=LZX:100
COMPRESS_SOLID=LZMS:100
if [[ ${ARG_COMPRESS_SOLID_FORCE+set} ]]; then
	[[ $ARG_COMPRESS_SOLID_FORCE == 1 ]] || COMPRESS_SOLID="$ARG_COMPRESS_SOLID_FORCE"
	EXTENSION=esd
	SKIP_WIMBOOT=1
elif [[ ${ARG_COMPRESS_SOLID+set} ]]; then
	[[ $ARG_COMPRESS_SOLID == 1 ]] || COMPRESS_SOLID="$ARG_COMPRESS_SOLID"
	EXTENSION=esd
elif [[ ${ARG_COMPRESS+set} ]]; then
	[[ $ARG_COMPRESS == 1 ]] || COMPRESS="$ARG_COMPRESS"
	EXTENSION=wim
elif [[ ${ARG_COMPRESS_NONE+set} ]]; then
	COMPRESS=none
	EXTENSION=wim
else
	COMPRESS=LZX:100
	EXTENSION=wim
fi

WIMOPTIMIZE_ARGS_WIM=(
	--check
	--recompress
	--compress "$COMPRESS"
	# we have to specify non-solid chunk because wimoptimize inherits it otherwise, breaking ESD->WIM conversion
	# (Microsoft tooling chokes on LZX/128K)
	--chunk-size 32K
)
# HACK: if --compress=none, wimlib does not recognize a --chunk-size, so drop it
if [[ $COMPRESS == none ]]; then
	unset WIMOPTIMIZE_ARGS_WIM[-1]
	unset WIMOPTIMIZE_ARGS_WIM[-1]
fi

WIMOPTIMIZE_ARGS_ESD=(
	--check
	--recompress
	--solid
	--solid-compress "$COMPRESS_SOLID"
	--solid-chunk-size 64M
	# we have to specify non-solid algo/chunk because wimoptimize inherits them otherwise, yielding counterintuitive results
	# (producing ESD files that report LZX/32K compression)
	--compress "$COMPRESS_SOLID"
	--chunk-size 128K
)

if [[ $EXTENSION == esd ]]; then
	log "Applying solid compression (ESD) with $COMPRESS_SOLID"
	WIMOPTIMIZE_ARGS=( "${WIMOPTIMIZE_ARGS_ESD[@]}" )
elif [[ $EXTENSION == wim ]]; then
	if [[ $COMPRESS != none ]]; then
		log "Applying editable compression (WIM) with $COMPRESS"
	else
		log "Applying editable format (WIM) without compression"
	fi
	WIMOPTIMIZE_ARGS=( "${WIMOPTIMIZE_ARGS_WIM[@]}" )
fi

if ! (( ${#ARG_FILES[@]} )); then
	log "No files provided -- assuming current directory ($(realpath --strip .))"
	ARG_FILES=(.)
fi

process_wimboot() {
	local file="$1" stem="${1%.*}"
	local -a args
	local out_ext out_file

	args=( "${WIMOPTIMIZE_ARGS_WIM[@]}" )
	out_ext="wim"
	out_file="$stem.$out_ext"

	log "Recompressing single file [wimboot]: $file -> $out_file"

	trace wimoptimize "${args[@]}" "$file" || return
	if [[ "$file" != "$out_file" ]]; then
		trace mv -v "$file" "$out_file" || return
	fi
	return 0
}

process_image() {
	local file="$1" stem="${1%.*}" in_ext="${1##*.}" in_join_ext
	local -a args
	local out_ext out_split_ext out_file tmp_file
	if [[ ! $SKIP_WIMBOOT && ${file##*/} == boot.* ]]; then
		process_wimboot "$file"
		return
	fi

	case "$in_ext" in
	swm) in_join_ext=wim ;;
	ssd) in_join_ext=esd ;;
	*) in_join_ext="$in_ext" ;;
	esac

	args=( "${WIMOPTIMIZE_ARGS[@]}" )
	out_ext="$EXTENSION"
	out_file="$stem.$out_ext"
	tmp_file="$stem.tmp.$in_join_ext"

	log "Recompressing single file: $file -> $out_file"
	local LIBSH_LOG_PREFIX="[${file##*/}]"

	local is_split=0
	local -a parts ref_parts
	case "$in_ext" in
	swm|ssd)
		is_split=1
		parts=( "$stem"[0-9]*."$in_ext" )
		ref_parts=( --ref "${stem}[0-9]*.${in_ext}" )
		;;
	esac

	local is_filtered=0
	case "${ARG_FILTER_DROP+set}${ARG_FILTER_KEEP+set}" in
	*set*) is_filtered=1 ;;
	esac

	local -a wimkeep wimdrop
	local wimlast

	if (( is_split || is_filtered )); then
		local -a lines
		local line

		_match() {
			# XXX: hack: crude way to distinguish between matching by image index and matching by name
			#      (--filter-drop 1 will drop image #1, but --filter-drop 100
			#       will drop an image whose name contains '100')
			if [[ $term =~ ^[0-9]+$ ]] && (( term < 100 )); then
				(( term == idx ))
			else
				[[ ${terms,,} == *${term,,}* ]]
			fi
		}

		wiminfo-short --machine "$file" \
			| readarray -t lines \
		|| return

		for line in "${lines[@]}"; do
			IFS=$'\t' read -r idx codename fullname version arch lang <<<"$line"
			IFS=$'\t' read -r idx terms <<<"$line"
			wimlast="$idx"

			local verdict=""
			if [[ ${ARG_FILTER_DROP+set} ]]; then
				verdict="${verdict:-keep}"
				for term in "${ARG_FILTER_DROP[@]}"; do
					_match && verdict=drop ||:
				done
			fi
			if [[ ${ARG_FILTER_KEEP+set} ]]; then
				verdict="${verdict:-drop}"
				for term in "${ARG_FILTER_KEEP[@]}"; do
					_match && verdict=keep ||:
				done
			fi
			verdict="${verdict:-keep}"

			case "$verdict" in
			keep) wimkeep+=("$idx") ;;
			drop) wimdrop+=("$idx") ;;
			esac
			dbg "${verdict^^}: image=$idx code=$codename name=${fullname@Q} version=${version@Q} arch=${arch} lang=$lang"
		done
		dbg "last=$wimlast keeping=$(join + "${wimkeep[@]}") dropping=$(join + "${wimdrop[@]}")"
	fi

	# only trigger an error if this is the user's fault
	if (( ${#wimdrop[@]} > 0 && ${#wimkeep[@]} < 1 )); then
		err "no images remaining!"
		return 1

	# if !is_split && !is_filtered, the image list won't be populated and this branch won't trigger,
	# but that's fine
	elif (( ${#wimkeep[@]} == 1 )); then
		log "one image remaining, running wimexport"
		trace wimexport "${args[@]}" "${ref_parts[@]}" "$file" "${wimkeep[0]}" "$out_file" || return
		trace rm -v "$file" "${parts[@]}" || return
		file="$out_file"

	else
		if (( is_split )); then
			log "split, joining"
			trace wimjoin "${WIMJOIN_ARGS[@]}" "$tmp_file" "$file" "${parts[@]}" || return
			trace rm -v "$file" "${parts[@]}" || return
			file="$tmp_file"
		fi

		if (( ${#wimdrop[@]} > 0 )); then
			log "have extra images, dropping"
			while (( ${#wimdrop[@]} > 0 )); do
				trace wimdelete --soft "$file" "${wimdrop[-1]}" || return
				unset wimdrop[-1]
			done
		fi

		wimoptimize "${args[@]}" "$file" || return
	fi

	if [[ "$file" != "$out_file" ]]; then
		trace mv -v "$file" "$out_file" || return
		file="$out_file"
	fi

	# FIXME: wimlib does not support split esd, TODO: find out if it is possible at all
	if [[ $ARG_SPLIT ]]; then
		case "$out_ext" in
		wim) out_split_ext=swm ;;
		# esd) out_split_ext=ssd ;;
		*) die "Unsupported output extension for split: ${out_ext@Q}" ;;
		esac
		out_file="$stem.$out_split_ext"

		unset LIBSH_LOG_PREFIX
		log "Splitting output: $file -> $out_file"

		trace wimsplit "${WIMSPLIT_ARGS[@]}" "$file" "$out_file" "$ARG_SPLIT" || return
	fi

	return 0
}

process_dir() {
	log "Recompressing directory: $1"

	local errs=0

	find "$1" \
		-type f \
		\( -name '*.wim' -or -name '*.esd' -or -name '*.swm' -or -name "*.ssd" \) \
		-not \( -name '*[0-9].swm' -or -name '*[0-9].ssd' \) \
	| while IFS= read -r file; do
		log "Processing file: $file"

		# XXX hack
		filedir="$(dirname "$file")"
		filebase="$(basename "$file")"
		stem="${filebase%.*}"
		ext="${filebase##*.}"

		shopt -s nullglob
		# catch split-wim subsequent volumes, if they exist
		replacing=( "$file" "$filedir/$stem"[0-9]."$ext" )
		adoptable=( "$2/$stem".* )
		if [[ ${#adoptable[@]} == 1 ]]; then
			log "XXX: hack: instead of $(join "+" "${replacing[@]}"), adopting ${adoptable[0]}"
			rm -vf "${replacing[@]}" || { (( ++errs )); continue; }
			cp -av "${adoptable[0]}" -t "$filedir" || { (( ++errs )); continue; }
			continue
		fi
		# XXX end hack

		process_image "$file" || (( ++errs ))
	done

	if (( errs )); then
		err "Failed to process $errs images in the directory"
		return 1
	fi
	return 0
}

process_iso() {
	eval "$(ltraps)"

	local out
	if [[ $ARG_OUTPUT ]]; then
		out="$ARG_OUTPUT"
	elif [[ $ARG_REPLACE ]]; then
		out="$1"
	elif [[ $COMPRESS != none ]]; then
		out="${1%%?(.orig).iso}.$EXTENSION.iso"
	else
		out="${1%%?(.orig).iso}.none.iso"
	fi

	log "Remastering ISO file: $1 -> $out"

	local label
	label="$(isoinfo -j UTF-8 -d -i "$1" | sed -nr 's/^Volume (set )?id: (.+)$/\2/p' | head -n1)" || return

	work_dir="$(mktempdir -d)" || return
	ltrap "rm -rf '$work_dir'"

	7z x -o"$work_dir" "$1" || return
	process_dir "$work_dir" "$(dirname "$1")" || return

	if [[ $ARG_DROP_OEM && -e "$work_dir/sources/\$OEM\$" ]]; then
		log "Remastering ISO file: stripping sources/\$OEM\$"
		rm -vr "$work_dir/sources/\$OEM\$"
	fi

	local out_tmp="$(dn_slash "$out").$(bn "$out").XXXXXXXXXX.tmp"
	out_tmp="$(mktemp -u "$out_tmp")" || return
	ltrap "rm -f '$out_tmp'"

	mkwiniso "$work_dir" "$out_tmp" "$label" || return
	mv -fT "$out_tmp" "$out" || return
	luntrap
}

errs=0
for file in "${ARG_FILES[@]}"; do
	if [[ -d "$file" ]]; then
		if ! process_dir "$file"; then
			err "Failed to process directory: $file"
			(( ++errs ))
		fi
	elif [[ "${file,,}" == *.iso ]]; then
		if ! process_iso "$file"; then
			err "Failed to process ISO file: $file"
			(( ++errs ))
		fi
	elif [[ "${file,,}" =~ \.(wim|esd|swm|ssd)$ ]]; then
		if ! process_image "$file"; then
			err "Failed to process WIM file: $file"
			(( ++errs ))
		fi
	else
		err "Unknown item: $file"
		(( ++errs ))
	fi
done

if (( errs )); then
	err "Total $errs errors"
	exit 1
fi
exit 0
