#!/bin/bash -e

. lib.sh

tmp=''
cleanup() {
	if [[ "$tmp" ]]; then
		rm -rf "$tmp"
		tmp=''
	fi
}
trap cleanup EXIT

declare -A DIR_TEMPLATES FILE_TEMPLATES

path_compute_acl() {
	if ! [[ -e "$file" ]]; then
		die "Bad file: '$file'"
	fi

	parent="${file%/*}"; if [[ $parent == $file ]]; then parent=.; fi
	if ! [[ -d "$parent" ]]; then
		die "Bad parent: '$parent' (file: '$file')"
	fi

	if ! [[ ${DIR_TEMPLATES[$parent]} ]]; then
		sample="$parent/.tmp.$$.d"
		mkdir "$sample"

		DIR_TEMPLATES[$parent]="$(getfacl "$sample")"
		rm -d "$sample"

		sample="$parent/.tmp.$$.f"
		touch "$sample"
		FILE_TEMPLATES[$parent]="$(getfacl "$sample")"
		rm -f "$sample"
	fi
}

path_apply_acl() {
	parent="${file%/*}"; if [[ $parent == $file ]]; then parent=.; fi

	if [[ -d "$file" ]]; then
		template="${DIR_TEMPLATES[$parent]}"
	else
		template="${FILE_TEMPLATES[$parent]}"
	fi

	if ! [[ "$template" ]]; then
		die "Bad template for '$parent' (file: '$file')"
	fi

	if ! setfacl --set-file=- "$file" <<<"$template"; then
		die "Failed to reset ACLs: '$file'"
	fi
}

case "$1" in
-R|-r)
	shift
	exec find "$@" -execdir "$0" {} \+
	;;
esac

for file; do
	path_compute_acl "$file"
done

for file; do
	path_apply_acl "$file"
done
