#!/bin/bash -e

. lib.sh || exit 1

TARGET="$1"
ARGS=( "${@:2}" )

SSH_ARGS=(
	"${ARGS[@]}"
	-o BatchMode=yes
	-o ServerAliveInterval=15
)

SSHFS_ARGS=(
	"${SSH_ARGS[@]}"
	-o reconnect
	-o idmap=user
	-o transform_symlinks
	-o dir_cache=yes
	-o max_conns=8
	-o allow_root
)

if [[ "$TARGET" =~ ([^@]+@)?([^:]*)(:.+)? ]]; then
	USER="${BASH_REMATCH[1]%'@'}"
	HOST="${BASH_REMATCH[2]}"
	DIR="${BASH_REMATCH[3]#':'}"
else
	die "Cannot parse sshfs target: '$1'"
fi

USERHOST="${USER:+$USER@}${HOST}"
SYMBOLIC_USER="$(ssh "${SSH_ARGS[@]}" "$USERHOST" 'whoami')"
SYMBOLIC_USERHOST="${SYMBOLIC_USER}@${HOST}"

if [[ -z "$DIR" ]]; then
	SYMBOLIC_DIR="~"
elif ! [[ $DIR == /* ]]; then
	SYMBOLIC_DIR="~/$DIR"
else
	SYMBOLIC_DIR="$DIR"
fi

MOUNTPOINT="$HOME/mnt/${SYMBOLIC_USERHOST}/${SYMBOLIC_DIR##/}"
mkdir -p "$MOUNTPOINT"

UNIT="sshfs-$(systemd-escape "$SYMBOLIC_USER")-$(systemd-escape "$HOST")-$(systemd-escape "$DIR").service"
ACTIVE="$(systemctl --user is-active "$UNIT" || true)"
case "$ACTIVE" in
inactive)
	;;
failed)
	systemctl --user reset-failed "$UNIT"
	;;
active)
	systemctl --user status "$UNIT"
	exit
	;;
*)
	systemctl --user status "$UNIT"
	die "Invalid unit state for '$UNIT': '$ACTIVE'"
	;;
esac

SYSTEMD_RUN_ARGS=()
if [[ ${SSH_AUTH_SOCK+set} ]]; then
	SYSTEMD_RUN_ARGS+=( -E SSH_AUTH_SOCK )
fi

systemd-run \
	--user \
	--unit "$UNIT" \
	-p Type=forking \
	"${SYSTEMD_RUN_ARGS[@]}" \
	sshfs \
		"$USERHOST:$DIR" \
		"$MOUNTPOINT" \
		"${SSHFS_ARGS[@]}" \

