#!/bin/bash

set -eo pipefail
shopt -s lastpipe

# shellcheck source=../lib/lib.sh
. lib.sh

TARGET="${@:$#}"
ARGS=("${@:1:$#-1}")

call_virsh() {
	virsh "${ARGS[@]}" "$@"
}

call_virsh shutdown "$TARGET"

while ! call_virsh list --inactive | grep -q -w "$TARGET"; do
	sleep 1
done
sleep 1

call_virsh start "$TARGET"
