#!/bin/bash

. lib.sh || exit

_usage() {
	cat <<EOF
Usage: $0 [section] page [keyword]
EOF
}

if (( $# == 0 )); then
	die "Too few arguments"
elif (( $# == 1 )); then
	REQUEST="$1"
else
	if [[ $1 =~ ^[0-9] ]]; then
		REQUEST="$2.$1"
		shift 2
	elif [[ $2 =~ ^[0-9] ]]; then
		REQUEST="$1.$2"
		shift 2
	else
		REQUEST="$1"
		shift 1
	fi
	REQUEST+="#$*"
fi

URL="https://man.archlinux.org/man/$REQUEST"
exec xdg-open "$URL"
