#!/bin/bash

set -eo pipefail
shopt -s lastpipe
. lib.sh

_usage() {
	cat <<EOF
Usage: $0 [-r|-R] [-f] DATASET-GLOB@SNAPSHOT...
EOF
}


#
# args
#

declare -A _args=(
	[-h|--help]=ARG_USAGE
	[-r|-R|-f]="pass=ARGS_PASS"
	[-n]="ARG_DRY_RUN"
	[--]=ARGS
)
parse_args _args "$@" || usage
[[ ! $ARG_USAGE ]] || usage


#
# main
#

declare -A DATASET_TARGETS
declare -a ROLLBACK_TARGETS

zfs list -Ho name -t snapshot \
	| readarray -t SNAPSHOTS

for g in "${ARGS[@]}"; do
	[[ $g == ?*@?* ]] || die "snapshot glob must contain @"

	for s in "${SNAPSHOTS[@]}"; do
		# $g is a glob
		if [[ "$s" == $g ]]; then
			[[ $s == ?*@?* ]] || die "Internal error: invalid snapshot name: ${s@Q}"

			dataset="${s%@*}"
			snapshot="${s#*@}"
			existing="${DATASET_TARGETS["$dataset"]}"
			if [[ $existing ]]; then
				die "Invalid arguments: cannot rollback ${dataset@Q} to @${existing} and @${snapshot} at the same time"
			fi
			DATASET_TARGETS["$dataset"]="$snapshot"
			ROLLBACK_TARGETS+=("$s")
		fi
	done
done

# cute hack:
# $dry_run is interposed between xargs' flags and command line
# - if not dry-run, $dry_run contains a "verbose" flag to xargs
#   (semantically, it is the trailing part of xargs' flags)
# - if dry-run, the "verbose" argument is _replaced_ with an echo command
#   (semantically, it is the leading part of xargs' command line)
# the `--` is added purely to illustrate this
dry_run=(-t --)
if [[ ${ARG_DRY_RUN+set} ]]; then
	dry_run=(-- echo "(would execute)")
fi

if [[ ${ROLLBACK_TARGETS+set} ]]; then
	log "Rolling back ${#ROLLBACK_TARGETS[@]} datasets"
	xargs -r -d'\n' -n1 -P$(nproc) "${dry_run[@]}" zfs rollback "${ARGS_PASS[@]}" \
		< <(printf "%s\n" "${ROLLBACK_TARGETS[@]}")
else
	warn "Nothing matched"
fi




