#!/bin/bash

set -eo pipefail
shopt -s lastpipe
. lib.sh

_usage() {
	cat <<EOF
Usage: $0 [-u] [-f] DATASET-GLOB@SNAPSHOT... @NEW-SNAPSHOT
EOF
}


#
# args
#

declare -A _args=(
	[-h|--help]=ARG_USAGE
	[-u|-f]="pass=ARGS_PASS"
	[-n]="ARG_DRY_RUN"
	[--]=ARGS
)
parse_args _args "$@" || usage
[[ ! $ARG_USAGE ]] || usage

if (( ${#ARGS[@]} < 2 )); then
	usage "not enough positional arguments, at least 2 expected"
fi

ARG_NEW_NAME="${ARGS[-1]}"
ARG_GLOBS=( "${ARGS[@]:0:${#ARGS[@]}-1}" )

# we require a useless leading `@` in the final argument as a mollyguard,
# to make sure it is indeed the target snapshot name rather than an unlucky glob
# (in case the user forgot to specify the actual target name)
if [[ $ARG_NEW_NAME != @* ]]; then
	usage "new snapshot name must start with @"
fi
ARG_NEW_NAME="${ARG_NEW_NAME#@}"


#
# main
#

declare -A DATASET_TARGETS
declare -a RENAME_TARGETS

zfs list -Ho name -t snapshot \
	| readarray -t SNAPSHOTS

for g in "${ARG_GLOBS[@]}"; do
	[[ $g == ?*@?* ]] || die "snapshot glob must contain @"
	for s in "${SNAPSHOTS[@]}"; do
		# $g is a glob
		if [[ "$s" == $g ]]; then
			[[ $s == ?*@?* ]] || die "Internal error: invalid snapshot name: ${s@Q}"
			dataset="${s%@*}"
			snapshot="${s#*@}"
			existing="${DATASET_TARGETS["$dataset"]}"
			if [[ $existing ]]; then
				s1="$dataset@$existing"
				s2="$dataset@$snapshot"
				die "Invalid arguments: cannot rename both ${s1@Q} and ${s2@Q} to @${ARG_NEW_NAME} at the same time"
			fi
			DATASET_TARGETS["$dataset"]="$snapshot"
			RENAME_TARGETS+=("$s")
		fi
	done
done

rename_pairs() {
	local src
	for src in "${RENAME_TARGETS[@]}"; do
		dataset="${src%@*}"
		dest="$dataset@$ARG_NEW_NAME"
		printf "%s\n" "$src" "$dest"
	done
}

# cute hack:
# $dry_run is interposed between xargs' flags and command line
# - if not dry-run, $dry_run contains a "verbose" flag to xargs
#   (semantically, it is the trailing part of xargs' flags)
# - if dry-run, the "verbose" argument is _replaced_ with an echo command
#   (semantically, it is the leading part of xargs' command line)
# the `--` is added purely to illustrate this
dry_run=(-t --)
if [[ ${ARG_DRY_RUN+set} ]]; then
	dry_run=(-- echo "(would execute)")
fi

if [[ ${RENAME_TARGETS+set} ]]; then
	log "Renaming ${#RENAME_TARGETS[@]} datasets"
	xargs -r -d'\n' -n2 -P$(nproc) "${dry_run[@]}" zfs rename "${ARGS_PASS[@]}" \
		< <(rename_pairs)
else
	warn "Nothing matched"
fi





