#!/bin/bash

set -eo pipefail
shopt -s lastpipe

say() {
	echo "${0##*/}: $*" >&2
}

git_dir() {
	git "$@" rev-parse --git-dir
}

git rebase "$@" || true

while [[ -d "$(git_dir)/rebase-merge" ]]; do
	if ! git diff-files --quiet; then
		say "launching interactive shell"
		say "to continue, resolve and stage conflicts and exit 0"
		say "to abort, exit 1"
		if "$SHELL" -i; then
			# dance to capture exit code of $SHELL (cannot use ! in the condition)
			:
		else
			rc=$?
			git rebase --abort
			exit $rc
		fi
	else
		say "no conflicts left, continuing"
	fi

	# if the user not just staged the resolution but continued the rebase, play along
	if ! [[ -d "$(git_dir)/rebase-merge" ]]; then
		break
	fi

	# also play along if the index turned out empty
	if git diff-index --quiet HEAD --; then
		git rebase --continue || true
	else
		git rebase --skip || true
	fi
done
