#!/bin/bash

set -eo pipefail
shopt -s lastpipe

git_dir="$(git rev-parse --git-dir)"
cd "$git_dir"
git show-ref | while read hash ref; do
  if ! [[ -e $ref ]]; then
    echo "echo $hash > \"$ref\""
    if ! [[ -d ${ref%/*} ]]; then
      mkdir -p "${ref%/*}"
    fi
    echo "$hash" > "$ref"
  fi
done
echo "rm -f packed-refs"
rm -f packed-refs
