#!/bin/bash -e

#
# git-gc-min -- remove as much junk as possible while modifying as few packs as possible
#

git \
	-c gc.bigPackThreshold=100M \
	-c gc.reflogExpire=now \
	-c gc.reflogExpireUnreachable=now \
	gc --prune=now "$@"
