#!/bin/bash

set -eo pipefail
shopt -s lastpipe

say() {
	echo "${0##*/}: $*" >&2
}


git rebase "$@" && exit 0 || rc=$?

GIT_DIR="$(git rev-parse --git-dir)"
while [[ -d "$GIT_DIR/rebase-merge" ]]; do
	if ! git diff-files --quiet; then
		say "launching interactive shell"
		say "to continue, resolve and stage conflicts and exit 0"
		say "to abort, exit 1"
		"$SHELL" -i && rc=0 || rc=$?
		if (( rc != 0 )); then
			git rebase --abort || true
			break
		fi
	else
		say "no conflicts left, continuing"
	fi

	rc=0

	# if the user not just staged the resolution but finished the rebase, play along
	if ! [[ -d "$GIT_DIR/rebase-merge" ]]; then
		break
	fi

	# also play along if the index turned out empty
	if git diff-index --quiet HEAD --; then
		git rebase --skip || rc=$?
	else
		git rebase --continue || rc=$?
	fi
done

exit $rc
