#!/hint/bash

set -eo pipefail
shopt -s lastpipe

log() {
	echo ":: $*" >&2
}

err() {
	echo "E: $*" >&2
}

die() {
	err "$@"
	exit 1
}

usage() {
	if (( $# )); then
		echo "${0##*/}: $*" >&2
		echo >&2
	fi
	_usage >&2
	exit 1
}

_usage() {
	cat <<EOF
Usage: ${0##*/} [-d|--dir TMP-DIR]

Options:
	-d, --dir=TMP-DIR	Use TMP-DIR as the scratch directory
				to offload builds to [${TMP_ROOT@Q}]
EOF
}


#
# functions
#

process_one_dir() {
	local no_subdir
	while (( $# )); do
		case "$1" in
		--no-subdir) no_subdir=1 ;;
		-*) die "Invalid arg: ${1@Q}" ;;
		*) break ;;
		esac
		shift
	done

	local srcdir="./$1" dstdir
	if [[ $no_subdir ]]
	then dstdir="$tmpdir"
	else dstdir="$tmpdir/$1"
	fi

	if [[ -d "$srcdir" && ! -L "$srcdir" ]]; then
		if ! [[ -d "$dstdir" ]]; then
			log "Moving ${srcdir@Q} to ${dstdir@Q}"
			mkdir -vp "${dstdir%/*}"
			mv "$srcdir" -T "$dstdir"
		else
			log "Removing ${srcdir@Q} as ${dstdir@Q} already exists"
			rm -rf "$srcdir"
		fi
	elif [[ -e "$srcdir" ]]; then
		rm -vrf "$srcdir"
	fi

	mkdir -vp "$dstdir" "${srcdir%/*}"
	ln -vsf "$dstdir" -T "$srcdir"
}

# $1: source directory (.)
# $2: target directory (~/tmp/...)
# output: $tmpdir
setup_tmpdir() {
	local what="$1" where="$2"
	local subpath tag
	declare -g tmpdir

	subpath="$(realpath -qe --relative-to="$HOME" --relative-base="$HOME" "$what")"
	tag="$(systemd-escape "$subpath")"
	tag="${tag//'\x'??/'-'}"
	tmpdir="$where/$tag"
}


#
# args
#

TMP_ROOT="$HOME/tmp/big/build"

if args=$(getopt -o 'd:' --long 'dir:' -n "${0##*/}" -- "$@"); then
	eval set -- "$args"
else
	usage
fi
unset args

while :; do
	case "$1" in
	-d|--dir) shift; TMP_ROOT="$1" ;;
	--) shift; break ;;
	*) die "getopt error" ;;
	esac
	shift
done

case "$#" in
0) ;;
*) usage "unexpected positional arguments" ;;
esac
