#!/usr/bin/env python3

import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('key_type', choices=[ 'rsa', 'ec' ])
parser.add_argument('key_file')
args, remainder = parser.parse_known_args()

os.execvp(
	'openssl',
	[ 'openssl', args.key_type, '-in', args.key_file, '-out', args.key_file ] + remainder
)
