#!/bin/bash
# Source: http://crunchbang.org/forums/viewtopic.php?pid=137566#p137566

colors=($(xrdb -query | sed -n 's/.*color\([0-9]\)/\1/p' | sort -nu | cut -f2))

echo -e "\e[1;37m
     BLK        RED        GRN        YEL        BLU        MAG        CYN        WHT
────────────────────────────────────────────────────────────────────────────────────────
\e[0m"

for i in {0..7}; do echo -en "\e[$((30+$i))m █ $(printf "%7s" "${colors[i]}") \e[0m"; done; echo
for i in {8..15}; do echo -en "\e[1;$((22+$i))m █ $(printf "%7s" "${colors[i]}") \e[0m"; done; echo

echo -e "\e[1;37m
────────────────────────────────────────────────────────────────────────────────────────\e[0m"
